### ISSUE TITLE
Opening Project - Missing Scripts on all objects in Scene.

### ISSUE THREAD

**Issue by keiranlovett** [Will-S-Dev/Unity-Parkour-Example#1]
Using 2019.2.10f1

**Comment by Hertzole** [comment]
It seems @Will-S-Dev forgot to include the .meta files which causes this.

**Comment by Will-S-Dev** [comment]
My apologies. I will update ASAP. Did you find any workarounds?

**Comment by Will-S-Dev** [comment]
I have added the .meta files. Everything should be working fine now

**Comment by Hertzole** [comment]
It seems you're still missing the .meta files. This may seem like an obvious thing but do you have your meta files visible? (In Project Settings - Editor - Version Control/Mode and set to Visible Meta Files)

**Comment by Will-S-Dev** [comment]
Strange. I do see the meta files and upload everything. Maybe github is filtering out the meta files

**Comment by Will-S-Dev** [comment]
Meta files has been uploaded. Please tell me if you encounter any more issues

**Comment by Hertzole** [comment]
It works perfectly now, thanks!

**Comment by Will-S-Dev** [comment]
Awesome! I will be closing the issue now.
